---
title: Democracy Upgraded
name: Democracy Upgraded
timezone: CET
collections:
  crew:
    title: Crew
    output: false
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    is_post: true
    layout: page
    lang: sv
    permalink: /:title/
- scope:
    path: ''
    type: pages
  values:
    layout: page
    lang: sv
- scope:
    path: en
    type: pages
  values:
    layout: page
    lang: en
- scope:
    path: ''
    type: crew
  values:
    lang: sv
email: admin@digidemlab.org
baseurl:
url: https://democracyupgraded.org
author: Democracy Upgraded
twitter:
  username: digidemlab
facebook:
  publisher: digidemlab
logo: "/assets/images/logo.svg"
social:
  links:
  - https://twitter.com/digidemlab
  - https://www.facebook.com/digidemlab
  - https://www.instagram.com/digidemlab/
  - https://github.com/digidemlab
github_username: p-jo
repository: digidemlab/communityorganising.se
plugins:
- jemoji
- jekyll-seo-tag
- jekyll-menus
#- jekyll-feed
emptyArray: []
t:
  sv:
    mission: Democracy Upgraded tror på att förbättra, utveckla och nyskapa vår demokrati. Vi tror på att förflytta makt och mandat att formulera samhällets problem och lösningar.
    language: Svenska
    member:
    - title: Styrelsemedlem i Global Participatory Budgeting Hub.
      image: "/assets/images/logo-pbp.png"
      url: https://www.participatorybudgeting.org/globalpbhub/
    - title: Styrelsemedlem och medgrundare till internationella Consul Democracy
        Foundation.
      image: "/assets/images/logo-consul.png"
      url: https://consulproject.org
    - title: Utveckling av medborgardialog i Göteborg och Stockholm med stöd av Vinnova.
      image: "/assets/images/logo-vinnova.png"
      url: https://www.vinnova.se/
    project-title-start: Våra uppdrag
    project-title: Uppdrag
    project-related: Uppdrag inom
    project-related-more: Fler uppdrag inom
    project-intro: Vi utvecklar demokratiskt deltagande för allt från internationella institutioner och städer
       till lokalt föreningsliv.
    project-link: Läs mer om uppdraget
    more-projects: Våra projekt
    project-client: Uppdragsgivare
    project-duration: Projektperiod
    project-partners: Partners
    project-website: Webbplats
    services-title: Vi erbjuder
    more-services: Läs mer om våra tjänster
    news: Aktuellt
    news-related: Aktuellt inom
    more-news: Fler nyheter
    read-more: Läs mer
    contact-title: Vill du veta mer?
    contact-text: Kontakta oss för att diskutera gemensamma projekt eller få ett prisförslag
      på våra tjänster.
  en:
    mission: "Democracy Upgraded believes in improving, developing and innovating our democracy. We believe in shifting power and mandate to formulate society's problems and solutions. Therefore, we provide and develop methods for political and democratic innovation."
    language: English
    member:
    - title: Board member of Global Participatory Budgeting Hub.
      image: "/assets/images/logo-pbp.png"
      url: https://www.participatorybudgeting.org/globalpbhub/
    - title: Co-founder and board member of Consul Democracy Foundation.
      image: "/assets/images/logo-consul.png"
      url: https://consulproject.org
    - title: Developing new methods for citizen participation with the support of
        Vinnova.
      image: "/assets/images/logo-vinnova.png"
      url: https://www.vinnova.se/en/
    project-title-start: Projects
    project-title: Projects
    project-related: Projects about
    project-related-more: Other projects about
    project-intro: We develop participatory democracy for everything from international institutions and cities to local associations.
    project-link: Read about the project
    more-projects: More projects
    project-client: Client
    project-duration: Duration
    project-partners: Partners
    project-website: Website
    services-title: Our services
    more-services: Read more about our services
    news: News
    news-related: News about
    more-news: More news
    read-more: Read more
    contact-title: Get in touch!
    contact-text: Get in touch to discuss ideas for projects or cooperation.
